# Generated by Django 4.2.4 on 2023-08-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='чат-ID в телеграмме'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='имя в телеграмме'),
        ),
    ]
