# Generated by Django 4.2.4 on 2023-08-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_tg_chat_id_alter_user_tg_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(max_length=150, unique=True, verbose_name='чат-ID в телеграмме'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_username',
            field=models.CharField(max_length=150, verbose_name='имя в телеграмме'),
        ),
    ]
