# Generated by Django 4.2.4 on 2023-08-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_tg_chat_id_alter_user_tg_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tg_chat_id',
            new_name='tg_user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tg_username',
            new_name='tg_user_name',
        ),
    ]
