# Generated by Django 4.2.4 on 2023-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_tg_chat_id_user_tg_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_user_id',
            field=models.CharField(max_length=150, verbose_name='чат-ID в телеграмме'),
        ),
    ]
