# Generated by Django 4.2.4 on 2023-08-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_tg_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_user_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='user_id из телеграмме'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_user_name',
            field=models.CharField(max_length=150, verbose_name='username или first_name <last_name> из телеграмма'),
        ),
    ]
