# Generated by Django 4.2.4 on 2023-08-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_tg_user_id_alter_user_tg_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_user_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='user_id из телеграмма'),
        ),
    ]
