# Generated by Django 4.2.4 on 2023-08-11 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='интервал между выполнением привычек, суток'),
        ),
    ]
