# Generated by Django 4.2.4 on 2023-08-12 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_date_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 12), verbose_name='дата выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.time(11, 9, 11, 50047), verbose_name='время выполнения привычки'),
        ),
    ]
